version: '3.8'

services:
  eureka-server:
    build:
      context: ./backend/eureka-server
    ports:
      - "8761:8761"
    networks:
      - ombs-net

  auth-service:
    build:
      context: ./backend/auth-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/ombs_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Kushagra@20
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-server
    networks:
      - ombs-net

  user-service:
    build:
      context: ./backend/user-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/ombs_user?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Kushagra@20
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-server
    networks:
      - ombs-net

  matching-service:
    build:
      context: ./backend/matching-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/ombs_matching?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Kushagra@20
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-server
    networks:
      - ombs-net

  payment-service:
    build:
      context: ./backend/payment-service
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/ombs_payment?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Kushagra@20
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-server
    networks:
      - ombs-net

  feedback-service:
    build:
      context: ./backend/feedback-service
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/ombs_feedback?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Kushagra@20
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-server
    networks:
      - ombs-net

  report-service:
    build:
      context: ./backend/report-service
    ports:
      - "8086:8086"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/ombs_matching?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Kushagra@20
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-server
    networks:
      - ombs-net

  gateway-service:
    build:
      context: ./backend/gateway-service
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - eureka-server
    networks:
      - ombs-net

  angular-portal:
    build:
      context: ./frontend/angular-portal
    ports:
      - "4200:80"
    depends_on:
      - gateway-service
    networks:
      - ombs-net

  react-analytics:
    build:
      context: ./frontend/react-analytics
    ports:
      - "4300:80"
    depends_on:
      - gateway-service
    networks:
      - ombs-net

networks:
  ombs-net:
    driver: bridge
